apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models-pvc
  namespace: llm-inference
  labels:
    app.kubernetes.io/name: llm-models
    app.kubernetes.io/part-of: llm-stack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: ""
  volumeName: llm-models-pv
